In [1]:
import pandas as pd 
import numpy as np
df = pd.read_csv('data/carprices.csv')
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [2]:
dummies = pd.get_dummies(df['Car Model'])
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [3]:
merged = pd.concat([df,dummies],axis = 'columns')
merged

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [4]:
final = merged.drop(['Car Model','Mercedez Benz C class'], axis='columns')
final

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [5]:
X = final.drop(['Sell Price($)'], axis='columns')
X = X.values
X

array([[69000,     6,     0,     1],
       [35000,     3,     0,     1],
       [57000,     5,     0,     1],
       [22500,     2,     0,     1],
       [46000,     4,     0,     1],
       [59000,     5,     1,     0],
       [52000,     5,     1,     0],
       [72000,     6,     1,     0],
       [91000,     8,     1,     0],
       [67000,     6,     0,     0],
       [83000,     7,     0,     0],
       [79000,     7,     0,     0],
       [59000,     5,     0,     0]], dtype=int64)

In [6]:
y = final['Sell Price($)']
y = y.values
y

array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
       22000, 20000, 21000, 33000], dtype=int64)

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [8]:
model.fit(X,y)

LinearRegression()

In [9]:
model.score(X,y)

0.9417050937281083

## Price of mercedez benz that is 4 yr old with mileage 45000

In [10]:
model.predict([[4500,4,0,0]])

array([51981.26203334])

## Price of BMW X5 that is 7 yr old with mileage 86000

In [11]:
model.predict([[86000,7,0,1]])

array([11080.74313219])

## LinearRegression model by train_test_split method

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=30)

In [13]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8755788480523449

## Use K Fold cross validation to measure accuracy of our LinearRegression model


In [14]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=10)

cross_val_score(LinearRegression(), X, y, cv=cv)

array([ 0.86753705,  0.55688692,  0.80175102,  0.83810639, -4.39435759])